### ISSUE TITLE
Compatibility with Mithril 1.0

### ISSUE THREAD

**Issue by jussiarpalahti** [owengalenjones/moria#1]
Hi @owengalenjones.

I made a ClojureScript library for Mithril some time back: https://github.com/jussiarpalahti/mathom/

I only just noticed your library when I got asked about differences between it and mine: https://github.com/jussiarpalahti/mathom/issues/1

I was wondering if you had any plans to support Mithril 1.0 now that it has been published?

Also, latest ClojureScript has better support for JavaScript interoperability, especially with modules. Mithril could probably be supported directly, without having to make separate Cljsjs package. You had done that previously, so perhaps it could possibly be upgraded anyway. Cljs module support's docs aren't quite clear what's the preferred route.

**Comment by owengalenjones** [comment]
@jussiarpalahti hello!

I had not planned on supporting 1.0 which is probably irresponsible of me.  I had released this library when I was churning on which React-wrapping-front-end library to use.  At the time I was unaware of https://github.com/reagent-project/reagent + https://github.com/Day8/re-frame (which I ended up choosing) and burned by Om landed on Mithril with thoughts on porting to CLJS (what became Moria).

I couldn't figure out how to do state management as Mithril is of course built on Mutable data-structures.  I see in your issue that you had working apps with state-management; I'm curious how you had accomplished this?

Due to interest I will investigate what it would take to move this to support 1.0 and would be interested in hearing / incorporating how you managed state.

Thanks!

**Comment by veggiemonk** [comment]
This is awesome! Thanks

**Comment by jussiarpalahti** [comment]
Hi, @owengalenjones 

Before doing my own simple version for state management I read Om and re-frame docs. This is essentially it:
```clojure
(defn updatedb [fields value]
  (set! db (assoc-in db fields value))
  (.redraw js/m true))

(defn querydb [fields]
  (get-in db fields))
```

Db here is just a map, and a global one to boot (though apps can be instantiated with their own variables if need be). You can see one complete app at https://github.com/jussiarpalahti/repodoc/blob/master/src/cljs/repodoc/core.cljs or more barebones version in Mathom's core.cljs. Essentially I call querydb on beginning of templating functions with map key path and when events occur call updatedb with key path and new data.

Mithril (at least on 0.2) is OK with redraw spamming that can happen when many events occur during same time frame. Mithril calls your render function only once for every frame resulting on entirely new virtual DOM, but that's very cheap compared to complexity of other approaches. Reconciliation strategy should keep the effect of this tolerable because only changed parts of the vDOM get applied to real DOM. For my small apps there wasn't any point in introducing any optimization (though app db's API is already abstract enough to support things like memoization or tree retaining).

Mithril's virtual DOM you build with m function is by functional programming's definition immutable, I believe. It's essentially one function call (containing more function calls till entire DOM tree is built) that given the same arguments produces the same output (though my app db implementation does bring outside data into functions which isn't as pure as FP doctrine states...). Virtual DOM in Mithril is a list of JS objects containing more lists of JS objects. You could even skip using m and just create Mithril vDOM data structure directly like this library: https://www.npmjs.com/package/mithril-objectify

I've yet to actually write any code with new 1.0 Mithril, but what I've read it shouldn't require changes in my strategy. The bigger questions are finding a way to use its NPM module from Cljs and how to configure Figwheel or boot for latest Cljs.

BTW: Making time travel (snapshot of state is saved when change occurs and can be rolled back and forward) was a simple matter with my solution. I serialize app db to browser's local storage on every update. When code change reloads the page (using boot's live reload feature) I set the deserialized state onto app db and get back to where I was. It happens faster than I can cmd+tab to browser from Cursive and way better I have with React+Redux. This is tremendous boon when working on a specific feature because I can see code changes take effect without having to waste time on redoing input or waiting API requests (results of those are present in the stored app db).

Hope this helps!

**Comment by owengalenjones** [comment]
Hey guys, sorry about the radio silence, I was without a laptop for about a month and unable to really work on this or anything for the duration.  Beginning to really get started on supporting 1.0.1 now that I'm back in business.

**Comment by owengalenjones** [comment]
Have a snapshot version of 1.0.1-0 compatibility:

https://clojars.org/moria/versions/1.0.1-0-SNAPSHOT

https://github.com/owengalenjones/moria/tree/1.0.1-0

I think it should be mostly there for 1.0.1, I'm curious if there's more stuff you guys would want to see added?
